<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { onMounted, ref, computed } from 'vue'
import { useBookStore } from '@/stores/book'
import { useUserStore } from '@/stores/user'
import type { Character, Location, WorldRule } from '@/stores/book'
import BookSidebar from '@/components/workspace/BookSidebar.vue'
import StoryPageComponent from '@/components/workspace/StoryPage.vue'
import BeatInput from '@/components/workspace/BeatInput.vue'
import CharacterPanel from '@/components/workspace/CharacterPanel.vue'
import LocationPanel from '@/components/workspace/LocationPanel.vue'
import WorldRulesPanel from '@/components/workspace/WorldRulesPanel.vue'

const { t } = useI18n()
const bookStore = useBookStore()
const userStore = useUserStore()

const currentPageNr = ref(1)
const isGenerating = ref(false)
const activeTab = ref<'atlas' | 'summary'>('atlas')

const currentPage = computed(() =>
  bookStore.sortedPages.find((p) => p.pageNr === currentPageNr.value) ?? null
)

onMounted(async () => {
  await userStore.fetchProfile()
  // Navigate to the last page
  if (bookStore.sortedPages.length > 0) {
    const lastPage = bookStore.sortedPages[bookStore.sortedPages.length - 1]
    if (lastPage) {
      currentPageNr.value = lastPage.pageNr
    }
  }
})

function handleSelectPage(pageNr: number): void {
  currentPageNr.value = pageNr
}

function handleUpdateContent(content: string): void {
  const page = bookStore.pages.find((p) => p.pageNr === currentPageNr.value)
  if (page) {
    page.content = content
  }
}

function handleGenerate(beat: string, mood: string, _mentionedIds: string[]): void {
  isGenerating.value = true
  // Simulate generation delay (will connect to real API later)
  setTimeout(() => {
    const newPageNr = bookStore.sortedPages.length + 1
    bookStore.pages.push({
      bookId: bookStore.currentBook?.bookId ?? '',
      pageNr: newPageNr,
      content: `[Generated content based on: "${beat}"]\n\nThis page will be generated by Gemini AI using the sliding window prompt with your world rules, rolling summary, and the last two pages as context.`,
      userNote: beat,
      targetMood: mood || 'Neutral',
      orderIndex: newPageNr,
    })
    currentPageNr.value = newPageNr
    isGenerating.value = false
  }, 1500)
}

function handleAddCharacter(char: Omit<Character, 'charId' | 'bookId'>): void {
  bookStore.characters.push({
    charId: `char-${Date.now()}`,
    bookId: bookStore.currentBook?.bookId ?? '',
    ...char,
  })
}

function handleToggleCharacter(charId: string): void {
  const char = bookStore.characters.find((c) => c.charId === charId)
  if (char) {
    char.isActive = !char.isActive
  }
}

function handleRemoveCharacter(charId: string): void {
  bookStore.characters = bookStore.characters.filter((c) => c.charId !== charId)
}

function handleAddLocation(loc: Omit<Location, 'locId' | 'bookId'>): void {
  bookStore.locations.push({
    locId: `loc-${Date.now()}`,
    bookId: bookStore.currentBook?.bookId ?? '',
    ...loc,
  })
}

function handleRemoveLocation(locId: string): void {
  bookStore.locations = bookStore.locations.filter((l) => l.locId !== locId)
}

function handleAddRule(rule: Omit<WorldRule, 'ruleId' | 'bookId'>): void {
  bookStore.worldRules.push({
    ruleId: `rule-${Date.now()}`,
    bookId: bookStore.currentBook?.bookId ?? '',
    ...rule,
  })
}

function handleRemoveRule(ruleId: string): void {
  bookStore.worldRules = bookStore.worldRules.filter((r) => r.ruleId !== ruleId)
}

function handleNewBook(): void {
  bookStore.clearCurrentBook()
}
</script>

<template>
  <main class="min-h-screen pt-16">
    <!-- Loading state -->
    <div v-if="bookStore.isLoading" class="flex items-center justify-center py-20">
      <p class="text-muted-foreground">{{ t('common.loading') }}</p>
    </div>

    <!-- No book selected -->
    <div
      v-else-if="!bookStore.currentBook"
      class="flex flex-col items-center justify-center py-20"
    >
      <h2 class="text-xl font-medium text-foreground">{{ t('workspace.welcome') }}</h2>
      <p class="mt-2 text-sm text-muted-foreground">{{ t('workspace.selectOrCreate') }}</p>
      <button
        class="mt-6 rounded-md bg-primary px-6 py-2.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
      >
        {{ t('story.newBook') }}
      </button>
    </div>

    <!-- Workspace layout -->
    <div v-else class="flex h-[calc(100vh-4rem)]">
      <!-- Left sidebar - Book navigation -->
      <div class="w-64 shrink-0 border-r border-border p-3">
        <BookSidebar
          :book="bookStore.currentBook"
          :pages="bookStore.sortedPages"
          :current-page-nr="currentPageNr"
          @select-page="handleSelectPage"
          @new-book="handleNewBook"
        />
      </div>

      <!-- Center - Story pages + Beat input -->
      <div class="flex flex-1 flex-col overflow-hidden">
        <div class="flex-1 overflow-y-auto p-6">
          <div class="mx-auto max-w-3xl space-y-6">
            <!-- Current page -->
            <StoryPageComponent
              v-if="currentPage"
              :page="currentPage"
              @update:content="handleUpdateContent"
            />

            <div v-else class="py-12 text-center text-muted-foreground">
              {{ t('workspace.noPages') }}
            </div>
          </div>
        </div>

        <!-- Beat input - fixed at bottom -->
        <div class="shrink-0 border-t border-border bg-background p-4">
          <div class="mx-auto max-w-3xl">
            <BeatInput
              :characters="bookStore.characters"
              :locations="bookStore.locations"
              :is-generating="isGenerating"
              @generate="handleGenerate"
            />
          </div>
        </div>
      </div>

      <!-- Right sidebar - Atlas (Characters, Locations, Rules) -->
      <div class="w-80 shrink-0 overflow-y-auto border-l border-border">
        <!-- Tab buttons -->
        <div class="sticky top-0 z-10 flex border-b border-border bg-background">
          <button
            class="flex-1 px-4 py-3 text-sm font-medium transition-colors"
            :class="
              activeTab === 'atlas'
                ? 'border-b-2 border-primary text-foreground'
                : 'text-muted-foreground hover:text-foreground'
            "
            @click="activeTab = 'atlas'"
          >
            {{ t('workspace.atlas') }}
          </button>
          <button
            class="flex-1 px-4 py-3 text-sm font-medium transition-colors"
            :class="
              activeTab === 'summary'
                ? 'border-b-2 border-primary text-foreground'
                : 'text-muted-foreground hover:text-foreground'
            "
            @click="activeTab = 'summary'"
          >
            {{ t('story.summary') }}
          </button>
        </div>

        <!-- Atlas panels -->
        <div v-if="activeTab === 'atlas'" class="space-y-4 p-4">
          <CharacterPanel
            :characters="bookStore.characters"
            @add="handleAddCharacter"
            @toggle="handleToggleCharacter"
            @remove="handleRemoveCharacter"
          />

          <LocationPanel
            :locations="bookStore.locations"
            @add="handleAddLocation"
            @remove="handleRemoveLocation"
          />

          <WorldRulesPanel
            :rules="bookStore.worldRules"
            @add="handleAddRule"
            @remove="handleRemoveRule"
          />
        </div>

        <!-- Summary panel -->
        <div v-else class="p-4">
          <div class="rounded-lg border border-border bg-card p-4">
            <h3 class="mb-2 text-sm font-semibold text-foreground">
              {{ t('workspace.rollingSummary') }}
            </h3>
            <p v-if="bookStore.summary" class="text-sm leading-relaxed text-muted-foreground">
              {{ bookStore.summary.rollingSummary }}
            </p>
            <p v-else class="text-sm italic text-muted-foreground">
              {{ t('workspace.noSummary') }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </main>
</template>
